INSERT INTO Users (name, studentNumber, password, role_admin, createdAt) VALUES ("tsunade", "b1164183", "konoha", 1, NOW());
INSERT INTO Users (name, studentNumber, password, role_admin, createdAt) VALUES ("konoha", "b1164150", "konoha", 0, NOW());
INSERT INTO Lectures (name, updatedAt) VALUES ("プログラミング入門", NOW());
INSERT INTO LecturesUsers (LectureId, UserId, updatedAt) VALUES (1, 1, NOW());
INSERT INTO LecturesUsers (LectureId, UserId, updatedAt) VALUES (1, 2, NOW());
INSERT INTO Subjects (name, content, LectureId, startAt, endAt) VALUES ("HelloWorld", "//HelloWorldを出力せよ", 1, NOW(), "2015/4/1");
INSERT INTO Subjects (name, content, LectureId, startAt, endAt) VALUES ("四則演算", "//四則演算せよ", 1, NOW(), "2015/4/1");
INSERT INTO Subjects (name, content, LectureId, startAt, endAt) VALUES ("関数", "//二つの引数の値を足したものを出力する関数を作成せよ", 1, NOW(), "2015/4/1");
INSERT INTO Subjects (name, content, LectureId, startAt, endAt) VALUES ("sort", "//バブルソートを行い、結果を出力する関数を作成せよ", 1, NOW(), "2015/4/1");
INSERT INTO Subjects (name, content, LectureId, startAt, endAt) VALUES ("fib", "//フィボナッチ数列のn番目の値を求める関数を作成せよ", 1, NOW(), "2015/4/1");
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (1, 1);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (1, 2);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (1, 3);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (1, 4);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (1, 5);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (2, 1);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (2, 2);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (2, 3);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (2, 4);
INSERT INTO SubmitStatuses (UserId, SubjectId) VALUES (2, 5);